version: "3.7"
services:
  proyectos-mono:
    container_name: proyectos-mono
    image: proyectos-mono:v1
    build:
      context: .
    ports:
      - "4001:4001"
    networks:
      - proyectos-app
networks:
  proyectos-app:
